In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
#sentences
sent = ['the glass of milk',
'the glass of juice',
'the cup of tea',
'I am a good boy',
'I am a good developer',
'understand the meaning of words',
'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
#define the vocabulary size
voc_size = 10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8766, 89, 4211, 7210],
 [8766, 89, 4211, 2542],
 [8766, 5897, 4211, 4128],
 [1473, 3091, 5998, 9386, 2768],
 [1473, 3091, 5998, 9386, 2763],
 [3995, 8766, 3828, 4211, 7035],
 [2720, 3514, 4870, 9386]]

In [6]:
#word embeddings representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8766   89 4211 7210]
 [   0    0    0    0 8766   89 4211 2542]
 [   0    0    0    0 8766 5897 4211 4128]
 [   0    0    0 1473 3091 5998 9386 2768]
 [   0    0    0 1473 3091 5998 9386 2763]
 [   0    0    0 3995 8766 3828 4211 7035]
 [   0    0    0    0 2720 3514 4870 9386]]


In [9]:
## feature representation
dim=10

In [10]:
model = Sequential()

model.add(
    Embedding(
        input_dim=voc_size,
        output_dim=dim,
        input_shape=(8,)
    )
)

model.compile(
    optimizer='adam',
    loss='mse'
)

model.summary()

/Users/shivakumargl/PycharmProjects/github ci/PythonProject/Simple_RNN/.venv/lib/python3.11/site-packages/keras/src/layers/core/embedding.py:126: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[[-0.01626372, -0.02631123, -0.03124274,  0.0197425 ,
          0.00733994, -0.00663681,  0.03646232, -0.03475187,
          0.03674128, -0.02498075],
        [-0.01626372, -0.02631123, -0.03124274,  0.0197425 ,
          0.00733994, -0.00663681,  0.03646232, -0.03475187,
          0.03674128, -0.02498075],
        [-0.01626372, -0.02631123, -0.03124274,  0.0197425 ,
          0.00733994, -0.00663681,  0.03646232, -0.03475187,
          0.03674128, -0.02498075],
        [-0.01626372, -0.02631123, -0.03124274,  0.0197425 ,
          0.00733994, -0.00663681,  0.03646232, -0.03475187,
          0.03674128, -0.02498075],
        [ 0.00466032, -0.00177382,  0.03874575, -0.04139354,
         -0.04587279,  0.03232639, -0.00738711,  0.01166423,
         -0.02518852, -0.03587372],
        [ 0.02303446,  0.04073564, -0.02163792,  0.00076895,
         -0.03725652, -0.01081229, -0.01055596,  0.00150501,
          0.04437418,  0.02567447],
        [-0.01477776,  0.01815734, -0.0473691 ,  0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 8766,   89, 4211, 7210], dtype=int32)

In [19]:
model.predict(embedded_docs[0:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step


array([[[-0.01626372, -0.02631123, -0.03124274,  0.0197425 ,
          0.00733994, -0.00663681,  0.03646232, -0.03475187,
          0.03674128, -0.02498075],
        [-0.01626372, -0.02631123, -0.03124274,  0.0197425 ,
          0.00733994, -0.00663681,  0.03646232, -0.03475187,
          0.03674128, -0.02498075],
        [-0.01626372, -0.02631123, -0.03124274,  0.0197425 ,
          0.00733994, -0.00663681,  0.03646232, -0.03475187,
          0.03674128, -0.02498075],
        [-0.01626372, -0.02631123, -0.03124274,  0.0197425 ,
          0.00733994, -0.00663681,  0.03646232, -0.03475187,
          0.03674128, -0.02498075],
        [ 0.00466032, -0.00177382,  0.03874575, -0.04139354,
         -0.04587279,  0.03232639, -0.00738711,  0.01166423,
         -0.02518852, -0.03587372],
        [ 0.02303446,  0.04073564, -0.02163792,  0.00076895,
         -0.03725652, -0.01081229, -0.01055596,  0.00150501,
          0.04437418,  0.02567447],
        [-0.01477776,  0.01815734, -0.0473691 ,  0.0

In [21]:
print(embedded_docs.shape)
print(embedded_docs[0].shape)
print(embedded_docs[0:1].shape)

(7, 8)
(8,)
(1, 8)


In [22]:
prediction = model.predict(embedded_docs[0:1], verbose=0)
print(prediction)

[[[-0.01626372 -0.02631123 -0.03124274  0.0197425   0.00733994
   -0.00663681  0.03646232 -0.03475187  0.03674128 -0.02498075]
  [-0.01626372 -0.02631123 -0.03124274  0.0197425   0.00733994
   -0.00663681  0.03646232 -0.03475187  0.03674128 -0.02498075]
  [-0.01626372 -0.02631123 -0.03124274  0.0197425   0.00733994
   -0.00663681  0.03646232 -0.03475187  0.03674128 -0.02498075]
  [-0.01626372 -0.02631123 -0.03124274  0.0197425   0.00733994
   -0.00663681  0.03646232 -0.03475187  0.03674128 -0.02498075]
  [ 0.00466032 -0.00177382  0.03874575 -0.04139354 -0.04587279
    0.03232639 -0.00738711  0.01166423 -0.02518852 -0.03587372]
  [ 0.02303446  0.04073564 -0.02163792  0.00076895 -0.03725652
   -0.01081229 -0.01055596  0.00150501  0.04437418  0.02567447]
  [-0.01477776  0.01815734 -0.0473691   0.01130826 -0.03836826
    0.0149245  -0.04689389 -0.03180735 -0.01155259  0.01523315]
  [-0.00891374 -0.04631105 -0.03765566 -0.00960116  0.03814406
    0.00214547 -0.00261983  0.01427146  0.017208

In [23]:
prediction = model.predict(embedded_docs[0:1], verbose=0)
print("Prediction:", prediction)
print("Score:", prediction[0][0])

Prediction: [[[-0.01626372 -0.02631123 -0.03124274  0.0197425   0.00733994
   -0.00663681  0.03646232 -0.03475187  0.03674128 -0.02498075]
  [-0.01626372 -0.02631123 -0.03124274  0.0197425   0.00733994
   -0.00663681  0.03646232 -0.03475187  0.03674128 -0.02498075]
  [-0.01626372 -0.02631123 -0.03124274  0.0197425   0.00733994
   -0.00663681  0.03646232 -0.03475187  0.03674128 -0.02498075]
  [-0.01626372 -0.02631123 -0.03124274  0.0197425   0.00733994
   -0.00663681  0.03646232 -0.03475187  0.03674128 -0.02498075]
  [ 0.00466032 -0.00177382  0.03874575 -0.04139354 -0.04587279
    0.03232639 -0.00738711  0.01166423 -0.02518852 -0.03587372]
  [ 0.02303446  0.04073564 -0.02163792  0.00076895 -0.03725652
   -0.01081229 -0.01055596  0.00150501  0.04437418  0.02567447]
  [-0.01477776  0.01815734 -0.0473691   0.01130826 -0.03836826
    0.0149245  -0.04689389 -0.03180735 -0.01155259  0.01523315]
  [-0.00891374 -0.04631105 -0.03765566 -0.00960116  0.03814406
    0.00214547 -0.00261983  0.014271

In [24]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
print(model.input_shape)

(None, 8)


In [12]:
import numpy as np
sample = np.array(embedded_docs[0]).reshape(1, 8)
print(sample.shape)
prediction = model.predict(sample)
print(prediction)

(1, 8)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[[[-0.01626372 -0.02631123 -0.03124274  0.0197425   0.00733994
   -0.00663681  0.03646232 -0.03475187  0.03674128 -0.02498075]
  [-0.01626372 -0.02631123 -0.03124274  0.0197425   0.00733994
   -0.00663681  0.03646232 -0.03475187  0.03674128 -0.02498075]
  [-0.01626372 -0.02631123 -0.03124274  0.0197425   0.00733994
   -0.00663681  0.03646232 -0.03475187  0.03674128 -0.02498075]
  [-0.01626372 -0.02631123 -0.03124274  0.0197425   0.00733994
   -0.00663681  0.03646232 -0.03475187  0.03674128 -0.02498075]
  [ 0.00466032 -0.00177382  0.03874575 -0.04139354 -0.04587279
    0.03232639 -0.00738711  0.01166423 -0.02518852 -0.03587372]
  [ 0.02303446  0.04073564 -0.02163792  0.00076895 -0.03725652
   -0.01081229 -0.01055596  0.00150501  0.04437418  0.02567447]
  [-0.01477776  0.01815734 -0.0473691   0.01130826 -0.03836826
    0.0149245  -0.04689389 -0.03180735 -0.01155259  0.01523315]
  [-0.00891374 -0.04631105 -0.03765566 -0.00960116  0.03814406
   

In [13]:
model.predict(sample)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step


array([[[-0.01626372, -0.02631123, -0.03124274,  0.0197425 ,
          0.00733994, -0.00663681,  0.03646232, -0.03475187,
          0.03674128, -0.02498075],
        [-0.01626372, -0.02631123, -0.03124274,  0.0197425 ,
          0.00733994, -0.00663681,  0.03646232, -0.03475187,
          0.03674128, -0.02498075],
        [-0.01626372, -0.02631123, -0.03124274,  0.0197425 ,
          0.00733994, -0.00663681,  0.03646232, -0.03475187,
          0.03674128, -0.02498075],
        [-0.01626372, -0.02631123, -0.03124274,  0.0197425 ,
          0.00733994, -0.00663681,  0.03646232, -0.03475187,
          0.03674128, -0.02498075],
        [ 0.00466032, -0.00177382,  0.03874575, -0.04139354,
         -0.04587279,  0.03232639, -0.00738711,  0.01166423,
         -0.02518852, -0.03587372],
        [ 0.02303446,  0.04073564, -0.02163792,  0.00076895,
         -0.03725652, -0.01081229, -0.01055596,  0.00150501,
          0.04437418,  0.02567447],
        [-0.01477776,  0.01815734, -0.0473691 ,  0.0